User authentication and space logic implemented
utkarshdagoat/Docops pull request #1
Opened 2023-10-03 19:26 UTC by utkarshdagoat

@poojasa7182

2023-10-04 04:25 UTC, utkarshdagoat commented
@Anupriya-Dey

2023-10-05 12:34 UTC, poojasa7182 requested changes

2023-10-05 12:34 UTC, poojasa7182 commented on backend/docops/__pycache__/__init__.cpython-311.pyc
pycache files to be added in gitignore

2023-10-05 12:34 UTC, poojasa7182 commented on backend/spaces/views.py
> +class RequestAPIView(generics.CreateAPIView):
Instead of adding as API view you can do the following - 
1. When a user makes a request, create a request model object.
2. The space admins can view all requests via get method - get method can be overridden to pass the space id as a pk and fetch all requests for that space.
3. When a space admin accepts or rejects a request then we can update the object's status by calling update method using the object's pk. 
Hence everything can be simply done using one ViewSet

2023-10-05 12:34 UTC, poojasa7182 commented on backend/spaces/views.py
I would suggest you to start by completing the code for all models, then writing the serializers, then generic viewsets, and then going into the specifics of it all, along with starting the frontend.

2023-11-04 01:12 UTC, merged